export interface IProduct{
    id: number,
    description: string,
    longDescription: string,
    brand: string,
    idCategories: string[],
    priority: number,
    visible: boolean,
    price: number,
    iva: number,
    discount: number | null,
    updatedAt: Date,
    urlImg: string,
    inStock: boolean,
    quantity?: number,
    tags: string[],
    showInHeroCarousel: boolean,
    attributes?: {
        content?: string,
        packaging?: string,
        services?: string,
        flavor?:string,
        colour?:string,
        performance?:string,
        textColor?: string,
    },
    relatedProductsIds?: number[],
    cashDiscount? : number,
}